import { DrizzleError } from '~/errors.ts';
import { readMigrationFiles } from '~/migrator.ts';
import { sql } from '~/sql/sql.ts';
import type { XataHttpDatabase } from './driver.ts';

export interface MigrationConfig {
	migrationsFolder: string;
	migrationsTable?: string;
}

/**
 * This function reads migrationFolder and execute each unapplied migration and mark it as executed in database
 *
 * NOTE: The Xata HTTP driver does not support transactions. This means that if any part of a migration fails,
 * no rollback will be executed. Currently, you will need to handle unsuccessful migration yourself.
 * @param db - drizzle db instance
 * @param config - path to migration folder generated by drizzle-kit
 */ export async function migrate<TSchema extends Record<string, unknown>>(
	db: XataHttpDatabase<TSchema>,
	config: MigrationConfig,
) {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';
	const migrationTableCreate = sql`
		CREATE TABLE IF NOT EXISTS ${sql.identifier(migrationsTable)} (
			id SERIAL PRIMARY KEY,
			hash text NOT NULL,
			created_at bigint
		)
	`;
	await db.session.execute(migrationTableCreate);

	const dbMigrations = await db.session.all<{
		id: number;
		hash: string;
		created_at: string;
	}>(
		sql`select id, hash, created_at from ${sql.identifier(migrationsTable)} order by created_at desc limit 1`,
	);

	const lastDbMigration = dbMigrations[0];

	for await (const migration of migrations) {
		if (!lastDbMigration || Number(lastDbMigration.created_at) < migration.folderMillis) {
			for (const stmt of migration.sql) {
				await db.session.execute(sql.raw(stmt));
			}

			await db.session.execute(
				sql`insert into ${
					sql.identifier(migrationsTable)
				} ("hash", "created_at") values(${migration.hash}, ${migration.folderMillis})`,
			);
		}
	}
}

/**
 * NOTE: The Xata HTTP driver does not support transactions. This means that if any part of a rollback fails,
 * no automatic rollback of the rollback will be executed.
 */
export async function rollback<TSchema extends Record<string, unknown>>(
	db: XataHttpDatabase<TSchema>,
	config: MigrationConfig,
	steps: number = 1,
) {
	const migrations = readMigrationFiles(config);
	const migrationsTable = config.migrationsTable ?? '__drizzle_migrations';

	const dbMigrations = await db.session.all<{
		id: number;
		hash: string;
		created_at: string;
	}>(
		sql`select id, hash, created_at from ${
			sql.identifier(migrationsTable)
		} order by created_at desc limit ${sql.raw(String(steps))}`,
	);

	if (dbMigrations.length === 0) {
		return;
	}

	for (const dbMigration of dbMigrations) {
		const meta = migrations.find((m) => m.hash === dbMigration.hash);
		if (!meta) {
			throw new DrizzleError({
				message: `Cannot rollback migration with hash ${dbMigration.hash}: migration file not found`,
			});
		}
		if (!meta.downSql || meta.downSql.length === 0) {
			throw new DrizzleError({
				message: `Cannot rollback migration ${dbMigration.hash}: no down SQL available. Add a .down.sql file alongside the migration.`,
			});
		}
		for (const stmt of [...meta.downSql].reverse()) {
			await db.session.execute(sql.raw(stmt));
		}
		await db.session.execute(
			sql`delete from ${sql.identifier(migrationsTable)} where hash = ${dbMigration.hash}`,
		);
	}
}
